# Generated by Django 2.2.7 on 2019-12-04 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('thumbnail', models.ImageField(upload_to='other_folder_name')),
                ('description', models.TextField(max_length=1000)),
                ('type', models.CharField(choices=[('github', 'Github'), ('behance', 'Behance')], max_length=120)),
                ('url', models.URLField()),
                ('demo_url', models.URLField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
